import type { ScaleDefinition } from '../types';

export const digitalHealthScale: ScaleDefinition = {
  id: 'digital_health',
  title: 'デジタル健康問診',
  internalName: 'デジタル健康外来 端末使用・睡眠スコア',
  description:
    'スマートフォン・SNS・AI等のデジタル環境に関連する端末使用状況と睡眠の状態を整理するための補助資料です。',
  sections: [
    {
      id: 'section_a',
      title: '端末使用状況',
      description: '昨日1日の端末使用について回答してください',
      maxScore: 30,
    },
    {
      id: 'section_b',
      title: '睡眠の状態',
      description: '昨夜から今朝の睡眠について回答してください',
      maxScore: 20,
    },
  ],
  questions: [
    // セクションA
    {
      id: 'a1',
      sectionId: 'section_a',
      text: '昨日、スマートフォン・タブレット・PCを合計何時間使いましたか？（仕事・学業での使用も含む）',
      type: 'scale',
      options: [
        { label: '1時間未満', value: 1 },
        { label: '1〜2時間', value: 2 },
        { label: '2〜4時間', value: 3 },
        { label: '4〜6時間', value: 4 },
        { label: '6〜8時間', value: 5 },
        { label: '8時間以上', value: 6 },
      ],
    },
    {
      id: 'a2',
      sectionId: 'section_a',
      text: 'そのうち、動画視聴（YouTube・TikTok・Netflix等）は何時間でしたか？',
      type: 'scale',
      options: [
        { label: 'ほぼなし', value: 0 },
        { label: '30分未満', value: 1 },
        { label: '30分〜1時間', value: 2 },
        { label: '1〜2時間', value: 3 },
        { label: '2〜4時間', value: 4 },
        { label: '4時間以上', value: 5 },
      ],
    },
    {
      id: 'a3',
      sectionId: 'section_a',
      text: 'SNS（X・Instagram・LINE等）の閲覧・投稿は何時間でしたか？',
      type: 'scale',
      options: [
        { label: 'ほぼなし', value: 0 },
        { label: '30分未満', value: 1 },
        { label: '30分〜1時間', value: 2 },
        { label: '1〜2時間', value: 3 },
        { label: '2時間以上', value: 4 },
      ],
    },
    {
      id: 'a4',
      sectionId: 'section_a',
      text: '昨夜、就寝前1時間以内にスマホ・タブレットを使いましたか？',
      type: 'scale',
      options: [
        { label: '使わなかった', value: 0 },
        { label: '少し使った（30分未満）', value: 1 },
        { label: 'かなり使った（30分以上）', value: 2 },
        { label: 'ほぼずっと使っていた', value: 3 },
      ],
    },
    {
      id: 'a5',
      sectionId: 'section_a',
      text: '昨日、端末を使っていない時間帯（食事・入浴・就寝前など）をどの程度作れましたか？',
      type: 'scale',
      options: [
        { label: '十分作れた', value: 0 },
        { label: 'ある程度作れた', value: 1 },
        { label: 'あまり作れなかった', value: 2 },
        { label: 'ほとんど作れなかった', value: 3 },
      ],
    },
    {
      id: 'a6',
      sectionId: 'section_a',
      text: '気がつくと予定より長く端末を使っていることがありましたか？',
      type: 'scale',
      options: [
        { label: 'なかった', value: 0 },
        { label: '1〜2回あった', value: 1 },
        { label: '3回以上あった', value: 2 },
        { label: '常にそうだった', value: 3 },
      ],
    },
    {
      id: 'a7',
      sectionId: 'section_a',
      text: 'AIツール（ChatGPT・Claude等）の使用はどの程度でしたか？',
      type: 'scale',
      options: [
        { label: '使わなかった', value: 0 },
        { label: '少し（30分未満）', value: 1 },
        { label: '1〜2時間程度', value: 2 },
        { label: '2時間以上', value: 3 },
      ],
    },
    {
      id: 'a8',
      sectionId: 'section_a',
      text: '昨日、端末を使っていて「頭が疲れた」「情報が多すぎた」と感じましたか？',
      type: 'scale',
      options: [
        { label: 'まったく感じなかった', value: 0 },
        { label: '少し感じた', value: 1 },
        { label: 'かなり感じた', value: 2 },
        { label: '強く感じた', value: 3 },
      ],
    },
    // セクションB
    {
      id: 'b1',
      sectionId: 'section_b',
      text: '昨夜、何時頃に布団・ベッドに入りましたか？',
      type: 'time_select',
      options: [
        { label: '21時前', value: '20:30' },
        { label: '21〜22時', value: '21:30' },
        { label: '22〜23時', value: '22:30' },
        { label: '23〜0時', value: '23:30' },
        { label: '0〜1時', value: '00:30' },
        { label: '1〜2時', value: '01:30' },
        { label: '2時以降', value: '02:30' },
      ],
    },
    {
      id: 'b2',
      sectionId: 'section_b',
      text: '布団に入ってから、眠りにつくまでどのくらいかかりましたか？',
      type: 'scale',
      options: [
        { label: '5分以内', value: 0 },
        { label: '5〜15分', value: 1 },
        { label: '15〜30分', value: 2 },
        { label: '30〜60分', value: 3 },
        { label: '1時間以上', value: 4 },
      ],
    },
    {
      id: 'b3',
      sectionId: 'section_b',
      text: '今朝、何時頃に起きましたか？',
      type: 'time_select',
      options: [
        { label: '5時前', value: '04:30' },
        { label: '5〜6時', value: '05:30' },
        { label: '6〜7時', value: '06:30' },
        { label: '7〜8時', value: '07:30' },
        { label: '8〜9時', value: '08:30' },
        { label: '9〜10時', value: '09:30' },
        { label: '10時以降', value: '10:30' },
      ],
    },
    {
      id: 'b4',
      sectionId: 'section_b',
      text: '夜中に目が覚めることがありましたか？',
      type: 'scale',
      options: [
        { label: 'なかった', value: 0 },
        { label: '1回', value: 1 },
        { label: '2〜3回', value: 2 },
        { label: '4回以上', value: 3 },
      ],
    },
    {
      id: 'b5',
      sectionId: 'section_b',
      text: '今朝起きたとき、眠れた感じ（熟眠感）はありましたか？',
      type: 'scale_5',
      options: [
        { label: 'まったくない', value: 1 },
        { label: '', value: 2 },
        { label: 'まあまあ', value: 3 },
        { label: '', value: 4 },
        { label: '十分あった', value: 5 },
      ],
    },
    {
      id: 'b6',
      sectionId: 'section_b',
      text: '今日の昼間、強い眠気を感じましたか？',
      type: 'scale',
      options: [
        { label: '感じなかった', value: 0 },
        { label: '少し感じた', value: 1 },
        { label: 'かなり感じた（活動に支障）', value: 2 },
        { label: '非常に強く感じた', value: 3 },
      ],
    },
    {
      id: 'b7',
      sectionId: 'section_b',
      text: '全体として、昨夜の睡眠に満足できましたか？',
      type: 'scale_5',
      options: [
        { label: 'まったく不満', value: 1 },
        { label: '', value: 2 },
        { label: 'まあまあ', value: 3 },
        { label: '', value: 4 },
        { label: '十分満足', value: 5 },
      ],
    },
  ],
};
